# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Williams Plumbing
email: adam@williamsplumbing.co.nz
description: > # this means to ignore newlines until "baseurl:"
  Coming soon.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://williamsplumbing.co.nz" # the base hostname & protocol for your site
twitter_username: williamsplumbing
github_username:  williamsplumbing

# Build settings
markdown: kramdown

github: [metadata]
kramdown:
 input: GFM
 hard_wrap: false
gems:
 - jekyll-coffeescript
